export const ethnicities = [
    { id: '1', name: 'Kinh' },
    { id: '2', name: 'Tày' },
    { id: '3', name: 'Thái' },
    { id: '4', name: 'Mường' },
    { id: '5', name: 'Hoa' },
    { id: '6', name: 'Khơ-me' },
    { id: '7', name: 'Nùng' },
    { id: '8', name: 'HMông' },
    { id: '9', name: 'Dao' },
    { id: '10', name: 'Gia-rai' },
    { id: '11', name: 'Ngái' },
    { id: '12', name: 'Chăm' },
    { id: '13', name: 'Co Tu' },
    { id: '14', name: 'Ba Na' },
    { id: '15', name: 'Bru - Vân Kiều' },
    { id: '16', name: 'Xơ Đăng' },
    { id: '17', name: 'Tà Ôi' },
    { id: '18', name: 'Ra Glai' },
    { id: '19', name: 'Churu' },
    { id: '20', name: 'Tà Thá' },
    { id: '21', name: 'Kơ Ho' },
    { id: '22', name: 'Lào' },
    { id: '23', name: 'Nơ Rong' },
    { id: '24', name: 'Khơ Mú' },
    { id: '25', name: 'MNông' },
    { id: '26', name: 'Sê Đăng' },
    { id: '27', name: 'Tày Trà' },
    { id: '28', name: 'Thổ' },
    { id: '29', name: 'Phù Lá' },
    { id: '30', name: ' Thái Đen' },
    { id: '31', name: ' Thái Trắng' },
    { id: '32', name: ' Thái Đỏ' },
    { id: '33', name: ' Thái Mường' },
    { id: '34', name: 'Mường Tháng' },
    { id: '35', name: 'Kháng' },
    { id: '36', name: 'Sán Chay' },
    { id: '37', name: 'Sán Dìu' },
    { id: '38', name: 'Tày Nùng' },
    { id: '39', name: ' Dao Đỏ' },
    { id: '40', name: ' Dao Quần Chẹt' },
    { id: '41', name: ' Sila' },
    { id: '42', name: ' Pa Kô' },
    { id: '43', name: ' Xinh Mun' },
    { id: '44', name: ' Ngái' },
    { id: '45', name: ' Tà Ôi' },
    { id: '46', name: ' Hre' },
    { id: '47', name: ' Bru' },
    { id: '48', name: ' Chăm' },
    { id: '49', name: ' Thái Đen' },
    { id: '50', name: ' Cơ Tu' },
    { id: '51', name: ' Xê Đăng' },
    { id: '52', name: ' Ba Na' },
    { id: '53', name: ' Gia Rai' },
    { id: '54', name: ' MNông' }
];
