export const occupations = [
    { id: 1, name: 'Bác sĩ' },
    { id: 2, name: 'Kỹ sư' },
    { id: 3, name: 'Giáo viên' },
    { id: 4, name: 'Nhân viên văn phòng' },
    { id: 5, name: 'Nghề nghiệp tự do' },
    { id: 6, name: 'Nhân viên bán hàng' },
    { id: 7, name: 'Nhà báo' },
    { id: 8, name: 'Nhà nghiên cứu' },
    { id: 9, name: 'Công nhân' },
    { id: 10, name: 'Nhà quản lý' },
    { id: 11, name: 'Người lao động phổ thông' },
    { id: 12, name: 'Chuyên viên tư vấn' },
    { id: 13, name: 'Người phục vụ' },
    { id: 14, name: 'Lập trình viên' },
    { id: 15, name: 'Thiết kế đồ họa' },
    { id: 16, name: 'Kiến trúc sư' },
    { id: 17, name: 'Marketing' },
    { id: 18, name: 'Nhân viên kế toán' },
    { id: 19, name: 'Dược sĩ' },
    { id: 20, name: 'Kinh doanh bất động sản' },
    { id: 21, name: 'Người lái xe' },
    { id: 22, name: 'Người quản lý dự án' },
    { id: 23, name: 'Hướng dẫn viên du lịch' },
    { id: 24, name: 'Nhà sản xuất' },
    { id: 25, name: 'Phát thanh viên' },
    { id: 26, name: 'Chuyên viên tài chính' },
    { id: 27, name: 'Công nghệ thông tin' },
    { id: 28, name: 'Nhân viên chăm sóc khách hàng' },
    { id: 29, name: 'Kỹ thuật viên' },
    { id: 30, name: 'Chuyên gia phân tích dữ liệu' },
    { id: 31, name: 'Người làm vườn' },
    { id: 32, name: 'Lao động phổ thông' },
    { id: 33, name: 'Quản lý sản xuất' },
    { id: 34, name: 'Thợ điện' },
    { id: 35, name: 'Thợ xây' },
    { id: 36, name: 'Người làm tóc' },
    { id: 37, name: 'Đầu bếp' },
    { id: 38, name: 'Chuyên viên pháp lý' },
    { id: 39, name: 'Giám đốc điều hành' },
    { id: 40, name: 'Nhà văn' },
    { id: 41, name: 'Chuyên gia an ninh mạng' },
    { id: 42, name: 'Nghệ sĩ' },
    { id: 43, name: 'Nhà tâm lý học' },
    { id: 44, name: 'Tài xế xe tải' },
    { id: 45, name: 'Quản lý nhân sự' },
    { id: 46, name: 'Người nghiên cứu thị trường' },
    { id: 47, name: 'Chuyên viên truyền thông' },
    { id: 48, name: 'Thợ sửa chữa' },
    { id: 49, name: 'Bảo vệ' },
    { id: 50, name: 'Nhân viên vận chuyển' },
    { id: 51, name: 'Thẩm phán' },
    { id: 52, name: 'Giáo sư' },
    { id: 53, name: 'Nhân viên bán hàng trực tuyến' },
    { id: 54, name: 'Thợ mộc' },
    { id: 55, name: 'Nhà đầu tư' },
    { id: 56, name: 'Kỹ thuật viên y tế' },
    { id: 57, name: 'Chuyên gia về môi trường' },
    { id: 58, name: 'Điều dưỡng viên' },
    { id: 59, name: 'Chuyên viên kỹ thuật' },
    { id: 60, name: 'Lao động tự do' },
    { id: 61, name: 'Người sáng tạo nội dung' },
    { id: 62, name: 'Người điều hành kinh doanh' },
    { id: 63, name: 'Thư ký' },
    { id: 64, name: 'Nhân viên bảo trì' },
    { id: 65, name: 'Chuyên viên giáo dục' },
    { id: 66, name: 'Nhà hoạt động xã hội' },
    { id: 67, name: 'Nhân viên hỗ trợ kỹ thuật' },
    { id: 68, name: 'Kỹ thuật viên sửa chữa điện tử' },
    { id: 69, name: 'Phục vụ bàn' },
    { id: 70, name: 'Kỹ thuật viên kiểm tra chất lượng' },
];
